name: Release and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: GY-CODING/devops/workflows/front/deploy.yml@main
    secrets: inherit
    with:
      domain: 'www.gycoding.com'
